remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "My CI SandBox"
description: "A project devoted to exploring CI and web deployment options."
logo: https://www.cs.odu.edu/~zeil/images/cslogo.gif
header_pages:
  - timestamp.md
  - javadoc/index.html
  - tests/test/index.html
skin: dark
  