# This workflow will build a Java project with Gradle

name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./imitation
      run: chmod +x gradlew
    - name: Build and test
      run: |
        ./gradlew build
      working-directory: ./imitation
    - name: Update website
      run: |
        git --version
        git branch -a
        git config --get remote.origin.url
        git checkout -b gh-pages origin/gh-pages  # make sure that gh-pages branch is available
        git checkout main
        ./gradlew deployReports
      working-directory: ./imitation
      
        
