# This workflow will build a Java project with Gradle

name: CI - build and test

on:
  push:
    branches: [ separateWebsite ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./imitation
      run: chmod +x gradlew
    - name: Build and test
      working-directory: ./imitation
      run: |
        ./gradlew build
    - name: Set up SSH agent
      run: |
        echo "${{ secrets.REPORTS_SSH_KEY }}"
    - name: Update website
      working-directory: ./imitation
      run: |
        eval $(ssh-agent -s -t 600)       
        ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")
        git config --global user.email "zeil@cs.odu.edu"
        git config --global user.name "Steven Zeil"
        ./gradlew deployReports
      
        
