# This workflow will build a Java project with Gradle

name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./imitation
      run: chmod +x gradlew
    - name: Build and test
      working-directory: ./imitation
      run: |
        ./gradlew build
    - name: Update website
      working-directory: ./imitation
      run: |
        ./gradlew copyWebsite # deployReports
        cd build/gh-pages
        ls
        git add .
        git status
        git commit -m "explicit commit from ci.yml"
        git push
        git status
        
      
        
