# This workflow will build a Java project with Gradle

name: CI - build and test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      working-directory: ./imitation
      run: chmod +x gradlew
    - name: Build and test
      working-directory: ./imitation
      run: |
        echo ./gradlew build
    - name: Update website
      working-directory: ./imitation
      run: |
        git config user.email "szeil@odu.edu"
        git config user.name "Steven Zeil"
        ./gradlew deployReports
        ls -a build/gh-pages
        cd build/gh-pages
        git status


      
        
